export const types = {
	authStartLogin: '[auth] Start login',
	authLogin: '[auth] Login',
	authLoginError: '[auth] Login Error',
	authStartRegister: '[auth] Start register',

	authChecking: '[auth] Checking login state',
	authCheckingFinish: '[auth] Finish checking login state',
	authLogin: '[auth] Login',
	authStartTokenRenew: '[auth] Start token renew',
	authLogout: '[auth] Logout',

	wishlistStartLoad: '[wishlist] Start load',
	wishlistLoaded: '[wishlist] Loaded',
	wishlistStartAddNew: '[wishlist] Start add',
	wishlistAddNew: '[wishlist] Add new',
	wishlistAdded: '[wishlist] Added',
	wishlistStartRemove: '[wishlist] Start remove',
	wishlistRemove: '[wishlist] Remove Item',
	wishlistRemoved: '[wishlist] Removed',
	wishlistStartClear: '[wishlist] Start clear',
	wishlistClear: '[wishlist] Clear',
	wishlistCleared: '[wishlist] Cleared',
	wishlistError: '[wishlist] Error',

	cartStartLoad: '[cart] Start load',
	cartLoaded: '[cart] Loaded',
	cartStartAdd: '[cart] Start add',
	cartAddNew: '[cart] Add new',
	cartAdded: '[cart] Added',
	cartStartRemove: '[cart] Start remove',
	cartRemove: '[cart] Remove',
	cartRemoved: '[cart] Removed',
	cartStartClear: '[cart] Start clear',
	cartClear: '[cart] Clear',
	cartCleared: '[cart] Cleared',
	cartError: '[cart] Error',
	cartStartQtyChange: '[cart] Start Qty change',
	cartQtyChange: '[cart] Qty change',
	cartQtyChanged: '[cart] Qty changed',
	cartStartPriceChange: '[cart] Start price change',
	cartPriceChange: '[cart] Price change',
	cartPriceChanged: '[cart] Price changed',

	orderStartCreate: '[order] Start create',
	orderCreated: '[order] Created',
	orderStartLoad: '[order] Start load',
	orderLoaded: '[order] Loaded',
	orderStartClear: '[order] Start clear',
	orderCleared: '[order] Cleared',
	orderError: '[order] Error',
};
